### ISSUE TITLE
Track information is unintelligible when using Spotify Connect

### ISSUE THREAD

**Issue by yanivmo** [ismailof/mediacontroller_plus#13]
The information is shown correctly when I play music on my laptop using Spotify app, but when I redirect the audio output using Spotify Connect the track information becomes instantly unreadable. Redirecting back to the laptop makes it right again.

![image](https://user-images.githubusercontent.com/3540009/85388174-75674480-b54e-11ea-83c6-04be5e701a62.png)

Using Spotify Connect means that in the Spotify app I ask to redirect the output to my phone. The app continues to show the track and its progress as before but doesn't play the audio on the laptop.

**Comment by ismailof** [comment]
That is unfortunately, Spotify not sending the right artist and title data to the MPRIS services (the common standard for linux multimedia info) when using Spotify Connect.

With normal playback:
![spotify_mpris](https://user-images.githubusercontent.com/16477746/85396905-e4df3300-b552-11ea-88b9-bee540388c4c.png)
With Spotify Connect (playing on remote device):
![spotify_mpris_connect](https://user-images.githubusercontent.com/16477746/85396902-e4469c80-b552-11ea-9c61-44155838b167.png)

Spotify support for MPRIS is quite abandoned and broken for some years (https://community.spotify.com/t5/forums/searchpage/tab/message?q=mpris) since they don't have linux environments as a priority, and other features like volume or song position don't work for spotify, and lately neither album covers.

**Comment by yanivmo** [comment]
Thank you for such a prompt and thorough answer!
