### ISSUE TITLE
Missing album image when playing from media sources (and other issues)

### ISSUE THREAD

**Issue by RAM53C** [ismailof/mediacontroller_plus#16]
When playing from sources like spotify, youtube (from browser) the album image is not being loaded. 
Also the icon tab bar isn't showing and isn't working at all.

**About my system:**
- Ubuntu 19.10 eoan using KDE 5.62.0 / Plasma 5.16.5
- Qt version 5.12.4
- Using mediacontroller_plus 0.2.5

![image](https://user-images.githubusercontent.com/20109157/94324132-571b4580-ff90-11ea-94eb-90c3588f86a8.png)

Thank you for the amazing work!

**Comment by RAM53C** [comment]
Well since I'm a developer, I decided to solve the album problem myself. 
The problem was that the album url provided by the metadata is not valid anymore. So, with a couple of code tweaks I made it work.

Here's the code:

![image](https://user-images.githubusercontent.com/20109157/94351443-63ff6e00-0050-11eb-8f0e-a51f1a63ee1e.png)

And album art sourcing:

![image](https://user-images.githubusercontent.com/20109157/94351471-b2147180-0050-11eb-9680-419f7374874d.png)

**Final result:**

![image](https://user-images.githubusercontent.com/20109157/94351497-00297500-0051-11eb-879d-c87079e338ae.png)

**Comment by ismailof** [comment]
Hi @RAM53C !

This is in fact a bug in spotify, which changed their url for album images but didn't update the url they report.
(https://community.spotify.com/t5/Desktop-Linux/MPRIS-cover-art-url-file-not-found/td-p/4920104)

Since we cannot expect a fix on their part and there are a lot of spotify users that suffer form it (me included), I've added a workaround in version 0.2.6 (d2e6946). Please, try it and tell me if that works for you. It should not affect the images from other providers that report their information right.

Thanks for reporting and giving me the hint to "fix" it! :smiley:

**Comment by RAM53C** [comment]
Hi @ismailof !

You're welcome! :smiley: 

I tested the plasmoid with spotify and it's working great!
The source tabs still don't work but I will try to write some code and see what I can do ahahah
